
# File: .github/workflows/azure_webapp.yml

on: 
  workflow_dispatch:

name: app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
      
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: ./app

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Azure webapp deploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.webapp }}
        package:  ${{ github.workspace }}/app
